repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.257'
    hooks:
      - id: ruff
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.301
    hooks:
    - id: pyright
      additional_dependencies: [equinox, diffrax, jax, jaxtyping, pandas, requests]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
    - id: nbqa-black
    - id: nbqa-ruff 
      args: ["--ignore=I001"]